version: "3.9"

services:
  resource_service:
    build: .
    command: uvicorn resource_service.app:app --host 0.0.0.0 --port 8001
    ports:
      - "8001:8001"

  grade_service:
    build: .
    command: uvicorn grade_service.app:app --host 0.0.0.0 --port 8002
    ports:
      - "8002:8002"

  web_app:
    build: .
    command: uvicorn web_app.app:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - resource_service
      - grade_service
